// HOME PAGE

// GUIDES PAGE
export enum GUIDE_TAGS {
  TAG1 = "tag1",
  TAG2 = "tag2",
  TAG3 = "tag3",
  TAG4 = "tag4",
  TAG5 = "tag5",
}

export const guides: any[] = [
  {
    title: "Guide title 1",
    description: "Guide description",
    date: "01.09.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG1, GUIDE_TAGS.TAG2],
  },
  {
    title: "Guide title 2",
    description: "Guide description",
    date: "24.08.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG1, GUIDE_TAGS.TAG2],
    featured: true,
  },
  {
    title: "Guide title 3",
    description: "Guide description",
    date: "31.08.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG5],
    featured: true,
  },
  {
    title: "Guide title 4",
    description: "Guide description",
    date: "11.08.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG3],
    featured: true,
  },
  {
    title: "Guide title 5",
    description: "Guide description",
    date: "02.06.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG5],
    featured: false,
  },
  {
    title: "Guide title 6",
    description: "Guide description",
    date: "14.07.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG1],
    featured: false,
  },
  {
    title: "Guide title 7",
    description: "Guide description",
    image: "/images/img-placeholder.jpg",
    date: "04.08.2023.",
    href: "/",
    tags: [GUIDE_TAGS.TAG4],
    featured: false,
  },
  {
    title: "Guide title 3",
    description: "Guide description",
    date: "29.07.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG5],
    featured: false,
  },
  {
    title: "Guide title 3",
    description: "Guide description",
    date: "14.06.2023.",
    href: "/",
    image: "/images/img-placeholder.jpg",
    tags: [GUIDE_TAGS.TAG5],
    featured: false,
  },
];
